### ISSUE TITLE
writing the test case for text translation page

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/monlam-web-testing#1]
### Description
This task is for UI testing. To check the UI functionality of the text-text translation page. Writing script to check each unit in this page.

### Completion Criteria

- Need to have test case for each unit functionality.
- It need to report the status of test execution either pass or failed

### Implementation Plan

- Get the scenarios in text translation page
- For each scenario find out different test case
- Find boundary value
- Design testcases

#### Create scenario
- [x] Login
- [x] Log out
- [x] Document disable when not login
- [x] Writing input text
- [x] Auto detection of input language
- [x] Translate button
- [x] Switch language translation
- [x] Output text
- [x] Audio
- [x] Edit button
- [x] Copy translated text
- [x] Share 
#### Test cases
- [x] Login 

- valid login
- invalid login
- [x] Logout
- [x] Document disabled when not login
- [x] Writing input text

- writing valid text
- writing more than 1000 char
- [x] Auto-detection of input language
- [x] Translate button
- hide when no input text
- disabled when input text has more than 1000 char
- when enter valid text
- [x] Output text
- [x] Audio
- [x] Edit button
- check if its editable or not
- cancel button
- save button
- [x] Copy translated text
- [x] Share 
- Copy share link
- Facebook share
- Twitter share
- Whatsapp share
- [x] Write script to above test case

**Comment by Karma-Tsering** [comment]
Add sub task to give more clearity

**Comment by ta4tsering** [comment]
making presentation on Testing strategy and the course taken on Playwright. will be presenting today at 4:00 pm
